on:
  workflow_call:

jobs:  
  scan_code:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$SONAR_TOKEN"
        env:
          SONAR_TOKEN: ${{ vars.SONAR_TOKEN }}
      # IMPORTANT: https://github.com/marketplace/actions/sonarcloud-scan#usage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ vars.SONAR_TOKEN }}