on:
  workflow_call:
    secrets:
      SONAR_TOKEN: { required: true } # *** ARE ALL OF THESE NEEDED?

jobs:
  scan_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}